name: Update Dependencies

on: [workflow_dispatch]

permissions:
  contents: write

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Create new branch
        run: |
          git checkout -b withUpdatedDependencies
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Set Git Config
        run: |
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"

      - name: Update Dependencies with gradle
        uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew versionCatalogUpdate 
        id: depup-id
        
      - name: Push if done successful
        run: |
          git add .
          git commit -m "updated deps"
          git push --set-upstream origin withUpdatedDependencies